export const residentData = [
  {
    residence_id: "PBR-28293992",
    name_title: "Mrs",
    firstName: "Oliseh",
    lastName: "Promise",
    address: "54 off, ekhewan road, isiloko, benin central",
    building_type: "Bungalow",
    facility_type: "One room self-contained",
    phone: ["08012345678", "08098765432"],
    email: "olisehpro@gmail.com",
    zone: "benin central",
    status: "active",
  },
  {
    residence_id: "PBR-27294399",
    name_title: "Mr",
    firstName: "Youth",
    lastName: "Hoamy",
    address: "54 ine junction, ugbowo",
    building_type: "Bungalow",
    facility_type: "One room self-contained",
    phone: ["08011111111", "08098765432"],
    email: "hoamy@gmail.com",
    zone: "Ugbowo",
    status: "active",
  },
  {
    residence_id: "PBR-94708399",
    name_title: "Dr",
    firstName: "Bassey",
    lastName: "Kolane",
    address: "9 tripod estate , ring road",
    building_type: "2-Floors",
    facility_type: "2-Bedroom",
    phone: ["08010000000", "09098765432"],
    email: "kolane@gmail.com",
    zone: "Ring road",
    status: "active",
  },
  {
    residence_id: "PBR-28293992",
    name_title: "Mrs",
    firstName: "Oliseh",
    lastName: "Promise",
    address: "54 off, ekhewan road, isiloko, benin central",
    building_type: "Bungalow",
    facility_type: "One room self-contained",
    phone: ["08012345678", "08098765432"],
    email: "olisehpro@gmail.com",
    zone: "benin central",
    status: "active",
  },
  {
    residence_id: "PBR-27294399",
    name_title: "Mr",
    firstName: "Youth",
    lastName: "Hoamy",
    address: "54 ine junction, ugbowo",
    building_type: "Bungalow",
    facility_type: "One room self-contained",
    phone: ["08011111111", "08098765432"],
    email: "hoamy@gmail.com",
    zone: "Ugbowo",
    status: "inactive",
  },
  {
    residence_id: "PBR-94708399",
    name_title: "Dr",
    firstName: "Bassey",
    lastName: "Kolane",
    address: "9 tripod estate , ring road",
    building_type: "2-Floors",
    facility_type: "2-Bedroom",
    phone: ["08010000000", "09098765432"],
    email: "kolane@gmail.com",
    zone: "Ring road",
    status: "banned",
  },
  {
    residence_id: "PBR-28293992",
    name_title: "Mrs",
    firstName: "Oliseh",
    lastName: "Promise",
    address: "54 off, ekhewan road, isiloko, benin central",
    building_type: "Bungalow",
    facility_type: "One room self-contained",
    phone: ["08012345678", "08098765432"],
    email: "olisehpro@gmail.com",
    zone: "benin central",
    status: "suspend",
  },
  {
    residence_id: "PBR-27294399",
    name_title: "Mr",
    firstName: "Youth",
    lastName: "Hoamy",
    address: "54 ine junction, ugbowo",
    building_type: "Bungalow",
    facility_type: "One room self-contained",
    phone: ["08011111111", "08098765432"],
    email: "hoamy@gmail.com",
    zone: "Ugbowo",
    status: "active",
  },
  {
    residence_id: "PBR-94708399",
    name_title: "Dr",
    firstName: "Bassey",
    lastName: "Kolane",
    address: "9 tripod estate , ring road",
    building_type: "2-Floors",
    facility_type: "2-Bedroom",
    phone: ["08010000000", "09098765432"],
    email: "kolane@gmail.com",
    zone: "Ring road",
    status: "active",
  },
];

export const fleetManage = [
    {
        firstName: "Boms",
        lastName: "Drake",
        email: "drake@gmail.com",
        gender: "male",
        phoneNumber: "+2348012345678",
        status: "active",
        date: "22-May-2023"
    },
    {
        firstName: "Boms",
        lastName: "Drake",
        email: "drake@gmail.com",
        gender: "male",
        phoneNumber: "+2348012345678",
        status: "active",
        date: "22-May-2023"
    },
    {
        firstName: "Boms",
        lastName: "Drake",
        email: "drake@gmail.com",
        gender: "male",
        phoneNumber: "+2348012345678",
        status: "active",
        date: "22-May-2023"
    },
    {
        firstName: "Boms",
        lastName: "Drake",
        email: "drake@gmail.com",
        gender: "male",
        phoneNumber: "+2348012345678",
        status: "active",
        date: "22-May-2023"
    },
    {
        firstName: "Boms",
        lastName: "Drake",
        email: "drake@gmail.com",
        gender: "male",
        phoneNumber: "+2348012345678",
        status: "active",
        date: "22-May-2023"
    },
    {
        firstName: "Boms",
        lastName: "Drake",
        email: "drake@gmail.com",
        gender: "male",
        phoneNumber: "+2348012345678",
        status: "active",
        date: "22-May-2023"
    },
    {
        firstName: "Boms",
        lastName: "Drake",
        email: "drake@gmail.com",
        gender: "male",
        phoneNumber: "+2348012345678",
        status: "active",
        date: "22-May-2023"
    },
    {
        firstName: "Boms",
        lastName: "Drake",
        email: "drake@gmail.com",
        gender: "male",
        phoneNumber: "+2348012345678",
        status: "active",
        date: "22-May-2023"
    },
]
